export enum MapEvent {
  onClick = "click",
  onDoubleClick = "dblclick",
  onRightClick = "rightclick",
  onMouseOut = "mouseout",
  onMouseOver = "mouseover",
  onMouseMove = "mousemove",
  onDrag = "drag",
  onDragStart = "dragstart",
  onDragEnd = "dragend",
  onIdle = "idle",
  onTilesLoaded = "tilesloaded",
  onTiltChanged = "tilt_changed",
  onZoomChanged = "zoom_changed",
  onBoundsChanged = "bounds_changed",
  onCenterChanged = "center_changed",
  onHeadingChanged = "heading_changed",
  onMapTypeIdChanged = "maptypeid_changed",
  onProjectionChanged = "projection_changed",
}
